
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace GithubReleaseManagement {
    using System;
    using Terminal.Gui;
    
    
    public partial class MyView : Terminal.Gui.Window {
        
        private Terminal.Gui.TextView releaseListTv;
        
        private Terminal.Gui.Label label;
        
        private Terminal.Gui.TextField prNumberTxtField;
        
        private Terminal.Gui.Label label2;
        
        private Terminal.Gui.TextField repoTxtField;
        
        private Terminal.Gui.Label label3;
        
        private Terminal.Gui.TextField orgUserTxtField;
        
        private Terminal.Gui.Label label4;
        
        private Terminal.Gui.CheckBox checkBox;
        
        private Terminal.Gui.Button getRlbtn;
        
        private void InitializeComponent() {
            this.getRlbtn = new Terminal.Gui.Button();
            this.checkBox = new Terminal.Gui.CheckBox();
            this.label4 = new Terminal.Gui.Label();
            this.orgUserTxtField = new Terminal.Gui.TextField();
            this.label3 = new Terminal.Gui.Label();
            this.repoTxtField = new Terminal.Gui.TextField();
            this.label2 = new Terminal.Gui.Label();
            this.prNumberTxtField = new Terminal.Gui.TextField();
            this.label = new Terminal.Gui.Label();
            this.releaseListTv = new Terminal.Gui.TextView();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Modal = false;
            this.IsMdiContainer = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "Release Maker | Press Ctrl+Q to quit";
            this.releaseListTv.Width = 325;
            this.releaseListTv.Height = 41;
            this.releaseListTv.X = 51;
            this.releaseListTv.Y = 0;
            this.releaseListTv.Visible = true;
            this.releaseListTv.AllowsTab = true;
            this.releaseListTv.AllowsReturn = true;
            this.releaseListTv.WordWrap = false;
            this.releaseListTv.Data = "releaseListTv";
            this.releaseListTv.Text = "Heya";
            this.releaseListTv.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.releaseListTv);
            this.label.Width = 5;
            this.label.Height = 1;
            this.label.X = 1;
            this.label.Y = 1;
            this.label.Visible = true;
            this.label.Data = "label";
            this.label.Text = "Enter PR Number";
            this.label.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label);
            this.prNumberTxtField.Width = 10;
            this.prNumberTxtField.Height = 1;
            this.prNumberTxtField.X = 1;
            this.prNumberTxtField.Y = 3;
            this.prNumberTxtField.Visible = true;
            this.prNumberTxtField.Secret = false;
            this.prNumberTxtField.Data = "prNumberTxtField";
            this.prNumberTxtField.Text = "";
            this.prNumberTxtField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.prNumberTxtField);
            this.label2.Width = 3;
            this.label2.Height = 1;
            this.label2.X = 1;
            this.label2.Y = 5;
            this.label2.Visible = true;
            this.label2.Data = "label2";
            this.label2.Text = "Enter Repo";
            this.label2.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label2);
            this.repoTxtField.Width = 10;
            this.repoTxtField.Height = 1;
            this.repoTxtField.X = 1;
            this.repoTxtField.Y = 7;
            this.repoTxtField.Visible = true;
            this.repoTxtField.Secret = false;
            this.repoTxtField.Data = "repoTxtField";
            this.repoTxtField.Text = "";
            this.repoTxtField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.repoTxtField);
            this.label3.Width = 4;
            this.label3.Height = 1;
            this.label3.X = 1;
            this.label3.Y = 9;
            this.label3.Visible = true;
            this.label3.Data = "label3";
            this.label3.Text = "Enter Orginization/User";
            this.label3.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label3);
            this.orgUserTxtField.Width = 10;
            this.orgUserTxtField.Height = 1;
            this.orgUserTxtField.X = 1;
            this.orgUserTxtField.Y = 11;
            this.orgUserTxtField.Visible = true;
            this.orgUserTxtField.Secret = false;
            this.orgUserTxtField.Data = "orgUserTxtField";
            this.orgUserTxtField.Text = "";
            this.orgUserTxtField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.orgUserTxtField);
            this.label4.Width = 3;
            this.label4.Height = 1;
            this.label4.X = 1;
            this.label4.Y = 13;
            this.label4.Visible = true;
            this.label4.Data = "label4";
            this.label4.Text = "Ignore Down Merge PRs";
            this.label4.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label4);
            this.checkBox.Width = 4;
            this.checkBox.Height = 1;
            this.checkBox.X = 1;
            this.checkBox.Y = 15;
            this.checkBox.Visible = true;
            this.checkBox.Data = "checkBox";
            this.checkBox.Text = "Yes";
            this.checkBox.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.checkBox.Checked = true;
            this.Add(this.checkBox);
            this.getRlbtn.Width = 25;
            this.getRlbtn.Height = 1;
            this.getRlbtn.X = 1;
            this.getRlbtn.Y = 17;
            this.getRlbtn.Visible = true;
            this.getRlbtn.Data = "getRlbtn";
            this.getRlbtn.Text = "Generate Release List";
            this.getRlbtn.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.getRlbtn.IsDefault = false;
            this.Add(this.getRlbtn);
        }
    }
}
